<?php
return array (
  'WEB_NAME' => '山西棣雅棠茶酒文化有限公司',
  'SEO_TITLE' => '茶酒文化',
  'SEO_KEYWORDS' => '茶酒',
  'SEO_DESCRIPTION' => '棣雅棠奔着为“家乡人民奉上一杯安全、放心的纯粮食酒”为初心，在茅台镇7.5平方公里数百家酒厂中甄选出一家最适合三晋儿女小酌的口粮酒——茅台•杜酱！
茅台•杜酱酒厂作为全国香柔酱香型白酒的代表企业，1983年至今经过不断的研发与努力获得了一大批爱酒之人的充分认可，多款酒在CCTV广告与各大地方卫视中频频出镜！',
  'WEB_LOGO' => '5fbcb56e1a3c2.png',
  'WEB_URL' => 'http://dev.gw.com',
  'WEB_VIDEO' => '/Uploads/video/1606203520545093.mp4',
  'WEB_CONTACTS' => '李将',
  'WEB_EMAIL' => '李将@163.com',
  'WEB_TEL' => '18518190359',
  'WEB_PHONE' => '18518190359',
  'WEB_HOT' => '18518190359',
  'WEB_ADD' => '山西省运城市稷山县',
  'WEB_ICP' => '',
  'WEB_COPYRIGHT' => 'CopyRight 2020 All Right Reserved ',
  'WEB_COUNT' => '',
  'WEB_BAIDU' => '',
  'IS_INQUIRY' => '0',
  'IS_EMAIL' => '0',
  'EMAIL_PORT' => '25',
  'EMAIL_HOST' => 'smtp.163.com',
  'EMAIL_USERNAME' => 'tdcms@163.com',
  'EMAIL_PASSWORD' => '123',
  'EMAIL_FROMNAME' => 'tdcms',
  'EMAIL_TO' => '852471958@qq.com',
  'SEND_WAY' => '1',
  'IS_ONLINE' => '0',
  'SKYPE_ACCOUNT' => '',
  'SKYPE_NAME' => '',
  'QQ_ACCOUNT' => '',
  'QQ_NAME' => '',
  'TAOBAO_ACCOUNT' => '',
  '1688_ACCOUNT' => '',
  'ALIBABA_ACCOUNT' => '',
  'ALIBABA_NAME' => '',
  'WEB_QRCODE' => '5fbcbc03f06a3.jpeg',
  'INDEX_NUM' => '4',
  'INDEX_TAGS' => '10',
  'LIST_PRONUM' => '8',
  'LIST_NEWNUM' => '8',
  'LIST_PHOTONUM' => '8',
  'LIST_DOWNNUM' => '8',
  'APPDIR' => '',
  'IS_THUMB' => '1',
  'MAXWIDTH' => '265',
  'MAXHEIGHT' => '199',
  'IS_WATER' => '0',
  'WATER_POSITION' => '9',
  'WATER_LOGO' => '5974bf8bdf97b.png',
  'WATER_ALPHA' => 100,
  'IS_TRANSLATE' => '0',
  'VERSION' => 'CNS57_08.06_webapp',
  'CNEN' => 'cn',
);
?>